### ISSUE TITLE
🔧 App Rework

### ISSUE THREAD

**Issue by fedetomassini** [fedetomassini/netscope#1]
## Tasks
- [x] New name.
- [x] Review the existing code structure.
- [x] Refactor components to improve readability and maintainability.
- [x] Redesign the UI for better usability and responsiveness.

**Comment by fedetomassini** [comment]
### Changes

- 🔧 Full app rework from ~CheckYourAPI~ => [Netscope](https://netscope.vercel.app).
